### ISSUE TITLE
Gradle 7 inompatiblity

### ISSUE THREAD

**Issue by chilicat** [TrigonicSolutions/gradle-rpm-plugin#44]
The plugin does not longer work with gradle 7:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.copy.CopyActionImpl.<init>(Lorg/gradle/api/internal/file/FileResolver;Lorg/gradle/api/internal/file/copy/CopySpecVisitor;)V
    at com.trigonic.gradle.plugins.rpm.Rpm$RpmCopyAction.<init>(Rpm.groovy:183)
    at com.trigonic.gradle.plugins.rpm.Rpm.<init>(Rpm.groovy:64)
    at com.trigonic.gradle.plugins.rpm.Rpm_Decorated.<init>(Unknown Source)
    at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:62)
    at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
    at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:113)
    ... 47 more

``
```

**Comment by tom-canova** [comment]
14:25:05.819 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.copy.CopyActionImpl.<init>(Lorg/gradle/api/internal/file/FileResolver;Lorg/gradle/api/internal/file/copy/CopySpecVisitor;)V
14:25:05.839 [ERROR] [org.gradle.BuildExceptionReporter]        at com.trigonic.gradle.plugins.rpm.Rpm$RpmCopyAction.<init>(Rpm.groovy:154)

This appears to be due to a change in gradle 1.7 to detect and handle duplicates in CopySpecs.  The constructor for CopyActionImpl now takes 3 arguments instead of 2.  The new argument is an instantiator which is used to create a container CopySpec which contains the visitor wrapped in a duplicate handling class and a Normalizing class.  

public CopyActionImpl(Instantiator instantiator, FileResolver resolver, CopySpecVisitor visitor) {
        this.instantiator = instantiator;
        this.resolver = resolver;
        this.root = instantiator.newInstance(CopySpecImpl.class, resolver, instantiator);
        this.mainContent = root.addChild();
        this.visitor = new DuplicateHandlingCopySpecVisitor(new NormalizingCopySpecVisitor(visitor));
    }

I'm going to use gradlew to enforce usage of gradle 1.6 for now on my builds which contain rpm tasks.

**Comment by david-resnick** [comment]
@seanjreilly @merscwog

Have either of you had a chance to work on getting this working with Gradle 1.7? Or had any further thoughts about it?

I'm planning on taking a stab at implementing something along the line of Sean's suggestion: "Do you think I could implement CopySpec, use a copy task to copy things into a temporary directory (with the absolute paths turned into relative paths), and then walk that directory to build the rpm?".
http://gradle.1045684.n5.nabble.com/Possible-Backwards-compatibility-problem-Gradle-1-7-crashes-with-RPM-plugin-tp5711630p5711638.html

**Comment by merscwog** [comment]
I have not gotten a chance to touch it.  My "gradle"-time has been spent doing final review stuff on the pending Gradle In Action book -- but that has a hard deadline of Aug 28th, so I'll be freeing up some time soon.

-Spencer

**Comment by david-resnick** [comment]
I spent some time on this today. It turns out that the modifications needed to get the rpm plugin working with 1.7 are trivial when working on a pre-debian support code base.

I haven't had a chance to test this in my own build yet, but this branch compiles and the tests all pass in it:
https://github.com/david-resnick/gradle-rpm-plugin/tree/gradle-1.7-without-debian-support

While not a fix that can be merged to master, I thought some might find this helpful.

**Comment by tom-canova** [comment]
I’ll give it a try.  I don’t require debian support, but definitely want to be able to use gradle 1.7 with the rpm plugin.

**Comment by merscwog** [comment]
I was able to confirm that these changes work fine for just rpm support (I also do not use the debian stuff).

-Spencer

**Comment by david-resnick** [comment]
Thanks for the confirmation! It seems that gradle-rpm-plugin is just the start of my gradle 1.7 incompatibilities, so I haven't been able to check actual RPM output yet.

**Comment by AlanKrueger** [comment]
Okay, I've put the Debian support commits onto the debian-support branch and reset master back to prior to those. I'll  look at pulling in your changes, @david-resnick.

**Comment by AlanKrueger** [comment]
Deployed a snapshot to https://oss.sonatype.org/content/repositories/snapshots, can you verify that this appears to be working?

**Comment by merscwog** [comment]
It can confirm that it appears to be working.

-Spencer

**Comment by merscwog** [comment]
Alan, do you need anyone else to confirm this works for them before publishing an offical 1.4 release without the debian support?  I have verified it will work for my needs, but need a non-snapshot version for actual approved usage.

-Spencer

**Comment by david-resnick** [comment]
I have created a pull request for this, based on the new master (without debian support):
https://github.com/TrigonicSolutions/gradle-rpm-plugin/pull/46

**Comment by AlanKrueger** [comment]
v1.4 has been released from Sonatype OSS staging and should appear in Maven Central soon.
